#!user/bin/python3
#import sys

i = 2
f = open(sys.argv[1], 'r')
while True:
    for line in f:
        if line % i == 0:
            j = round(line / i)
            print(f"{num}={i}*{j}")
            break
        if i == round(line/2) - 1:
            break
        i += 1
